/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlythuvien;

/**
 *
 * @author minh
 */
import DAO.DuLieuBang;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import DAO.*;
import Object.*;
//import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent;
public class QuanLyPhieuMuonSachPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhieuMuonSachPanel
     */
    public static String sql = "select * from PHIEUMUONSACH order by MAPHIEUMUONSACH asc";
    public QuanLyPhieuMuonSachPanel() {
        initComponents();
        showtb();
        setBackground(Color.white);
        
    }
    public final void showtb()
    {
    DuLieuBang.Load(sql, tbPhieuMuonSach);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaPhieuMuonSach = new javax.swing.JTextField();
        txtMaDocGia = new javax.swing.JTextField();
        jDateNgayMuon = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhieuMuonSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btLamMoi = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btThemMoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1074, 571));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(309, 394));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Mã phiếu mượn sách");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Mã độc giả");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Ngày mượn");

        txtMaPhieuMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuMuonSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPhieuMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, 240));

        tbPhieuMuonSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPhieuMuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MAPHIEUMUONSACH", "MADOCGIA", "NGAYMUON"
            }
        ));
        tbPhieuMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhieuMuonSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPhieuMuonSach);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 880, 260));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHIẾU MƯỢN SÁCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 909, 80));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 900, -1));

        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_search_30px.png"))); // NOI18N
        btTimKiem.setFocusable(false);
        btTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTimKiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        add(btTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 42, 40));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 490, 40));

        btLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_restart_40px.png"))); // NOI18N
        btLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLamMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });
        add(btLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        btCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_refresh_40px.png"))); // NOI18N
        btCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });
        add(btCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_cancel_40px.png"))); // NOI18N
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        btThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_plus_+_40px.png"))); // NOI18N
        btThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });
        add(btThemMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHI TIẾT MƯỢN SÁCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, -1, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xem CTPMS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, -1, 31));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tbPhieuMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhieuMuonSachMouseClicked
        // TODO add your handling code here:
        try{
            
           int row = this.tbPhieuMuonSach.getSelectedRow();
           String MArow = (String) (this.tbPhieuMuonSach.getModel().getValueAt(row, 0));
           String sql1 = " select * from PHIEUMUONSACH where MAPHIEUMUONSACH='"+MArow+"'";
           ResultSet rs = DuLieuBang.ShowTextField(sql1);
            if(rs.next())
           {             
               this.txtMaPhieuMuonSach.setText(rs.getString("MAPHIEUMUONSACH"));
               this.txtMaDocGia.setText(rs.getString("MADOCGIA"));
               this.jDateNgayMuon.setDate(rs.getDate("NGAYMUON"));
               
           }
           
    }                                      
 
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }//GEN-LAST:event_tbPhieuMuonSachMouseClicked

    
    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
        if(this.txtMaPhieuMuonSach.getText().length()!=0)
        {
            String sql2 = " select * from PHIEUMUONSACH where MAPHIEUMUONSACH like '%"+this.txtMaPhieuMuonSach.getText()+"%' ";
            DuLieuBang.Load(sql2, tbPhieuMuonSach);
        }
        else if(this.txtMaDocGia.getText().length()!=0)
        {
            String sql1 = " select * from PHIEUMUONSACH where MADOCGIA like '%"+this.txtMaDocGia.getText()+"%' ";
            DuLieuBang.Load(sql1, tbPhieuMuonSach);
        }
        else if(this.txtTimKiem.getText().length()!=0)
        {
            String sql ="SELECT * FROM PHIEUMUONSACH where MAPHIEUMUONSACH like'%"+this.txtTimKiem.getText()+"%' "
                    + "or MADOCGIA like '%"+this.txtTimKiem.getText()+"%'";
            DuLieuBang.Load(sql, tbPhieuMuonSach);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập","Thông báo",1);
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        // TODO add your handling code here:
        if(this.txtMaPhieuMuonSach.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã phiếu mượn sách","Thông báo",1);
        else
            if(this.txtMaDocGia.getText().length()==0)
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã độc giả","Thông báo",1);
        else
            {
        try
        {  
            int result = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn thêm phiếu mượn sách này","Xác nhận",JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION){
            PhieuMuonSach pms = new PhieuMuonSach();
            pms.setmAPHIEUMUONSACH(txtMaPhieuMuonSach.getText());
            pms.setmADOCGIA(txtMaDocGia.getText());
            if(jDateNgayMuon.getDate() != null )
            {
                java.util.Date utilStartDate = jDateNgayMuon.getDate();
                java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
                pms.setnGAYMUON(sqlStartDate);
            }
            
            PhieuMuonSachDAO.InsertPhieuMuonSach(pms);           
            JOptionPane.showMessageDialog(null, "Phiếu mượn sách được thêm vào thành công","Thông báo",1 );
            showtb();
        }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Lỗi!" + e.getMessage(),"Thông báo",1 );
                }
            }
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaPhieuMuonSach.getText().length()==0)
           JOptionPane.showMessageDialog(null,"Bạn cần chọn mã phiếu mượn sách để xóa","Thông báo",1);
        else
        {
        try{  
                
        int result = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa phiếu mượn sách này","Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
        PhieuMuonSachDAO.DeletePhieuMuonSach(txtMaPhieuMuonSach.getText());
        JOptionPane.showMessageDialog(null, "Phiếu mượn sách xóa thành công!", "Thông báo",1);
        showtb();
        } else {
        JOptionPane.showMessageDialog(null, "Phiếu mượn sách xóa thất bại!", "Thông báo",1);
        }
      } catch (Exception e){
          JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
      } 
      }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        if(this.txtMaPhieuMuonSach.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã phiếu mượn sách","Thông báo",1);
        else
        {
        try{  
            int result = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn cập nhật phiếu mượn sách này","Xác nhận",JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION){
            PhieuMuonSach pms = new PhieuMuonSach();
            pms.setmAPHIEUMUONSACH(txtMaPhieuMuonSach.getText());
            pms.setmADOCGIA(txtMaDocGia.getText());
            if(jDateNgayMuon.getDate() != null )
            {
                java.util.Date utilStartDate = jDateNgayMuon.getDate();
                java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
                pms.setnGAYMUON(sqlStartDate);
            }
            PhieuMuonSachDAO dao = new PhieuMuonSachDAO();
            dao.UpdatePhieuMuonSach(pms);           
            JOptionPane.showMessageDialog(null, "Phiếu mượn sách được sửa thành công","Thông báo",1 ); 
            showtb();
        }
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Lỗi!"+ e.getMessage(),"Thông báo",1 );
                }
        }
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaPhieuMuonSach.setText("");
        txtMaDocGia.setText("");
        jDateNgayMuon.setDate(null);
        txtTimKiem.setText("");
        showtb();
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new QuanLyChiTietMuonSach().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMaPhieuMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuMuonSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuMuonSachActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ThongTinMuonSach().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            String sql ="SELECT * FROM PHIEUMUONSACH where MAPHIEUMUONSACH like'%"+this.txtTimKiem.getText()+"%' "
                    + "or MADOCGIA like '%"+this.txtTimKiem.getText()+"%'";
            DuLieuBang.Load(sql, tbPhieuMuonSach);
        }
    }//GEN-LAST:event_txtTimKiemKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btThemMoi;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateNgayMuon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPhieuMuonSach;
    public static javax.swing.JTextField txtMaDocGia;
    public static javax.swing.JTextField txtMaPhieuMuonSach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
