/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlythuvien;

import Object.*;
import DAO.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Nguyen Linh,minh
 */
public class QuanLyCuonSach extends javax.swing.JFrame {

    /**
     * Creates new form CuonSach
     */
    public String sql =" select* from CUONSACH order by MASACH asc " ; 
    public QuanLyCuonSach() {
        initComponents();
        showtb();
        LoadCB();
         getContentPane().setBackground(Color.white); 
           setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
      public final void showtb()
    {
        DuLieuBang.Load(sql, tbCuonSach);
    }
     
      public void LoadCB()
    {
        String sql = "select TINHTRANG from CUONSACH group by TINHTRANG "; 
        try{
            Connection conn = Connect.getConnect();
            PreparedStatement pst= conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next())
            {
                this.cbTinhTrang.addItem(rs.getString("TINHTRANG"));
            }
        }catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        ThemMoi = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        Xoa = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        CapNhat = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        LamMoi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaDauSach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTinhTrang = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCuonSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_root_server_40px.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        ThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_plus_+_40px.png"))); // NOI18N
        ThemMoi.setFocusable(false);
        ThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(ThemMoi);
        jToolBar1.add(jSeparator3);

        Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_cancel_40px.png"))); // NOI18N
        Xoa.setFocusable(false);
        Xoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Xoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });
        jToolBar1.add(Xoa);
        jToolBar1.add(jSeparator4);

        CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_refresh_40px.png"))); // NOI18N
        CapNhat.setFocusable(false);
        CapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapNhatActionPerformed(evt);
            }
        });
        jToolBar1.add(CapNhat);
        jToolBar1.add(jSeparator5);

        LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_restart_40px.png"))); // NOI18N
        LamMoi.setFocusable(false);
        LamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LamMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(LamMoi);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 290, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), null));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Mã sách");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Mã đầu sách");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Tình trạng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMaDauSach)
                        .addComponent(cbTinhTrang, 0, 368, Short.MAX_VALUE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDauSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 730, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), null));

        tbCuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ SÁCH", "MÃ ĐẦU SÁCH", "TÌNH TRẠNG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbCuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCuonSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCuonSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 710, 180));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN SÁCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 60));

        TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_search_30px.png"))); // NOI18N
        TimKiem.setFocusable(false);
        TimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TimKiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 260, 40, 40));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 360, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapNhatActionPerformed
        // TODO add your handling code here:
        if(this.txtMaSach.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã  sách","Thông báo",1);
        else
        {
            try{   
                int result = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn cập nhật cuốn sách này","Xác nhận",JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION){
               CuonSach cs = new CuonSach();
               cs.setmASACH(txtMaSach.getText());
               cs.setmADAUSACH(txtMaDauSach.getText());
               cs.settINHTRANG(cbTinhTrang.getSelectedItem().toString());
               CuonSachDAO dao = new CuonSachDAO();
               dao.UpdateCuonSach(cs);           
               JOptionPane.showMessageDialog(null, "Mã sách được sửa thành công","Thông báo",1 );   
               showtb();
        }
            }
            catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Lỗi: "+ e.getMessage(),"Thông báo",1 );
                }    
            }
    }//GEN-LAST:event_CapNhatActionPerformed

    private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
        // TODO add your handling code here:
        if(this.txtMaSach.getText().length()!=0)
        {
            String sql1 = " select * from CUONSACH where MASACH like '%"+this.txtMaSach.getText()+"%' ";
            DuLieuBang.Load(sql1, tbCuonSach);
        }
        else if(this.txtMaDauSach.getText().length()!=0)
        {
            String sql2 = " select * from CUONSACH where MADAUSACH like '%"+this.txtMaDauSach.getText()+"%' ";
            DuLieuBang.Load(sql2, tbCuonSach);
        }
        else if(this.cbTinhTrang.getSelectedIndex()==0)
            {
                String sql3 = " select * from CUONSACH where TINHTRANG like '%"+this.cbTinhTrang.getSelectedItem()+"%' ";
                DuLieuBang.Load(sql3, tbCuonSach);    
            }
        else if(this.cbTinhTrang.getSelectedIndex()==1)
            {
                String sql3 = " select * from CUONSACH where TINHTRANG like '%"+this.cbTinhTrang.getSelectedItem()+"%' ";
                DuLieuBang.Load(sql3, tbCuonSach);    
            }  
        else if(this.txtTimKiem.getText().length()!=0)
        {
            String sql ="SELECT * FROM CUONSACH where MASACH like'%"+this.txtTimKiem.getText()+"%' "
                            + "or MADAUSACH like '%"+this.txtTimKiem.getText()+"%' "
                            + "or TINHTRANG like '%"+this.txtTimKiem.getText()+"%'";
                        DuLieuBang.Load(sql, tbCuonSach);
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập","Thông báo",1);
        }
        
    }//GEN-LAST:event_TimKiemActionPerformed

   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemMoiActionPerformed
        // TODO add your handling code here:
         if(this.txtMaSach.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã sách","Thông báo",1);
        else
            if(this.txtMaDauSach.getText().length()==0)
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã đầu sách","Thông báo",1);
        else
        {
            try{   
                int result = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn thêm cuốn sách này","Xác nhận",JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION){
                CuonSach cs = new CuonSach();
                cs.setmASACH(txtMaSach.getText());
                cs.setmADAUSACH(txtMaDauSach.getText());
                cs.settINHTRANG(cbTinhTrang.getSelectedItem().toString());
                CuonSachDAO.InsertCuonSach(cs);           
                JOptionPane.showMessageDialog(null, "Mã sách được thêm vào thành công","Thông báo",1 );    
                showtb();
        }
            }
            catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Lỗi: "+ e.getMessage(),"Thông báo",1 );
                }    
            }
    }//GEN-LAST:event_ThemMoiActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaSach.getText().length()==0)
           JOptionPane.showMessageDialog(null,"Bạn cần chọn mã sách để xóa","Thông báo",1);
        else
        {
        try{  
                
        int result = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa cuốn sách này","Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
        CuonSachDAO.DeleteCuonSach(txtMaSach.getText());
        JOptionPane.showMessageDialog(null, "Mã sách xóa thành công!", "Thông báo",1);
        showtb();
        } else {
        JOptionPane.showMessageDialog(null, "Mã sách xóa thất bại!", "Thông báo",1);
        }
      } catch (Exception e){
          JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
         
      }
        } 
    }//GEN-LAST:event_XoaActionPerformed

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
         txtMaSach.setText("");
        txtMaDauSach.setText("");
        cbTinhTrang.setSelectedItem(null);
        txtTimKiem.setText("");
        showtb();
    }//GEN-LAST:event_LamMoiActionPerformed

    private void tbCuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCuonSachMouseClicked
        // TODO add your handling code here:
         try{
            
           int row = this.tbCuonSach.getSelectedRow();
           String MArow = (String) (this.tbCuonSach.getModel().getValueAt(row, 0));
           String sql1 = " select * from CUONSACH where MASACH='"+MArow+"'";
           ResultSet rs = DuLieuBang.ShowTextField(sql1);
           
           if(rs.next())
           {
               
               this.txtMaSach.setText(rs.getString("MASACH"));
               this.txtMaDauSach.setText(rs.getString("MADAUSACH"));
               this.cbTinhTrang.setSelectedItem(rs.getString("TINHTRANG"));
               
           }
           
    }                                      
 
        catch(SQLException e)   
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbCuonSachMouseClicked

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            String sql ="SELECT * FROM CUONSACH where MASACH like'%"+this.txtTimKiem.getText()+"%' "
                            + "or MADAUSACH like '%"+this.txtTimKiem.getText()+"%' "
                            + "or TINHTRANG like '%"+this.txtTimKiem.getText()+"%'";
                        DuLieuBang.Load(sql, tbCuonSach);
        }
    }//GEN-LAST:event_txtTimKiemKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyCuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyCuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyCuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyCuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyCuonSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CapNhat;
    private javax.swing.JButton LamMoi;
    private javax.swing.JButton ThemMoi;
    private javax.swing.JButton TimKiem;
    private javax.swing.JButton Xoa;
    private javax.swing.JComboBox<String> cbTinhTrang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbCuonSach;
    private javax.swing.JTextField txtMaDauSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

   
}
